name: tuwaiq_project_pulse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.7.0
  get_it: ^7.7.0
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  pinput: ^5.0.0
  animated_notch_bottom_bar: ^1.0.3
  animated_snack_bar: ^0.4.0
  animated_splash_screen: ^1.3.0
  bottom_picker: ^2.8.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  file_picker: ^8.1.2
  flutter_pdfview: ^1.3.3
  shared_preferences: ^2.3.2
  video_player: ^2.9.1
  another_flutter_splash_screen: ^1.2.1
  url_launcher: ^6.3.0
  flutter_rating_bar: ^4.0.1
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
